Add more debug, and timeout on DHCP rather than silently waiting forever
avnet-iotconnect/iotc-azurertos-sdk pull request #50
Opened 2023-03-21 17:56 UTC by nmatthews-witekio

Split DHCP timeout into sections and add a delay.

The debug is helpful to track progress -- having a timeout is also useful -- rather than waiting indefinitely without any output (if there's a problem).

Not sure whether splitting the timeout into sections is necessary -- but it should give other threads a chance to update themselves and maybe IP related values, too.

2023-03-21 19:28 UTC, nbeck-witekio commented
This error checking is an improvement. We should free the DHCP resource too when failures occur and when it is finished with using nx_dhcp_delete()

2023-03-23 16:26 UTC, nik-markovic requested changes

2023-03-23 16:26 UTC, nik-markovic commented on samples/ck-rx65n/basic-sample/src/main.c
> +        printf("nx_dns_create failed: status = %d\r\n", status);
*status* is unsigned, it should be %u, or even better "0x%x" to be consistent with other status checks.

Needs to be updated other printfs.

I'm curuous though how did this even compile without warnings maybe make sure that we aren't ignoring compiler warnings in flags?

2023-03-23 16:26 UTC, nik-markovic commented on samples/ck-rx65n/basic-sample/src/main.c
> +    printf("...DHCP Finished\r\n");
Let's please not spam the logs. Ether one or the other message.

2023-03-23 16:26 UTC, nik-markovic commented on samples/ck-rx65n/basic-sample/src/main.c
> +        return;
I'm not 100% sure about this, but I am concerned about returning from a failure. If there's a problem, nothing will work anyways. It is safrer to stay lock the thread in this function. We can do tx_thread_sleep() in a forever loop. The sleep should also allow printfs to flush.

2023-03-23 16:26 UTC, nik-markovic commented on samples/ck-rx65n/basic-sample/src/main.c
> +    printf("nx_dhcp_create ok\r\n");
We should not be spamming the log and prininging all these status messages unless we are tracing. Please remove successful messages from the logs. You can leave important ones in.

It should be safe to assume that the outcome is success (print the last status message if needed) unlesss a stage failed, which will print the message in the log.

2023-03-28 15:33 UTC, nmatthews-witekio commented
Included and rebased in https://github.com/avnet-iotconnect/iotc-azurertos-sdk/pull/52

2023-03-28 15:33 UTC, closed without merging